#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSGrtNEjZYnjc2baxltgjBfTBIVHKlFlhQPS"
APP_SECRET: "nZKAOH+RWHSImFIf8pDY8ftYAAH6mmT/J8Zgh6Vy7zsEYxnalGsovWllTg1aR9UltUtX7eigscYLrVB70I6G7/rIUgPQU1+GUttOohBoGhLG131WZPT7UrlscTtarNrvitzXoGIwZylWcOaLlbROjELPsPmHNa+ia06nPr1c3MR3bpYNZ/Y="

#계좌번호 앞 8자리
CANO: "46595822"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1065229428294176798/srWmGE9s0AjiHeClCsBpZrs3XINCXG5nQgx8H9L6MjudFlerg7VSlMr69x5UEttjUNo7"